#Config file for the AutoPlant Plugin.
#Here you are able to change the in-game messages sent to the players while using the plugin*.

#*It is recommended that you keep the original messages for title formatting reasons.

#This field allows you to change the message when a sapling is broken:
Sapling: "That tree isn't fully grown yet!"

#This field allows you to change the message when a crop is broken:
Crop: "That crop isn't fully grown yet!"

#Once you have edited a title, be sure to reload the server!