name: AutoPlant
version: "5.3"
main: me.theminddroid.autoplant.AutoPlant
api-version: "1.13"
authors: [TheMindDroid]
description: Auto plants crops
depend: [WorldGuard]
commands:
  autoplant:
    description: Allows user to reload the plugin's config file.
    usage: /<command>
permissions:
  autoplant.bypass:
    default: false
  autoplant.reload:
    default: op